FROM node:18.17.1

WORKDIR /back-end/

ARG API_PORT
ARG JWT_KEY
ARG JWT_EXPIRATION
ARG URL_REDIS
ARG DB_HOST
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_NAME

ENV URL_REDIS=$URL_REDIS
ENV API_PORT=$API_PORT
ENV JWT_KEY=$JWT_KEY
ENV JWT_EXPIRATION=$JWT_EXPIRATION
ENV DB_HOST=${DB_HOST}
ENV DB_NAME=${DB_NAME}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}

COPY . .

RUN npm install && npm run build
# RUN npm run build
# RUN npm run runmigrations

EXPOSE $PORT

CMD ["sh", "-c", "npm run dev"]